# Generated by Django 3.2.5 on 2021-11-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.repository')),
            ],
        ),
    ]
