# Generated by Django 2.1.1 on 2019-06-19 17:24

from django.db import migrations
from apps.users.models import User


def create_initial_user(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    User.objects.create(
            email="bot@codecov.io",
            password="SoSecure!",
            last_name="Codecovski",
            first_name="Alex",
            is_admin=False)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_user),
    ]
