# Generated by Django 3.2.5 on 2021-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=20)),
                ('hash', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
