# Generated by Django 3.2.5 on 2021-11-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitdata',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
